[package]
name = "mcar"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = { version = "0.3", features = ["websocket", "compression"] }
rust_gpiozero = "0.2.1"
serde_json = "1.0"
futures-util = "0.3"
tokio-stream = "0.1"
opencv = "0.76.2"

[package.metadata.cross.build]
default-target = "armv7-unknown-linux-gnueabihf"

[package.metadata.cross.target.armv7-unknown-linux-gnueabihf]
dockerfile = "Dockerfile.cross"
